#!/bin/bash 

#  $$$$$$$$\  $$$$$$\  $$\      $$\ 
# \__$$  |$$  __$$\ $$$\    $$$ |
#    $$ |   $$ /  $$ |$$$$\  $$$$ |
#    $$ |   $$$$$$$$ |$$\$$\$$ $$ |
#    $$ |   $$  __$$ |$$ \$$$  $$ |
#    $$ |   $$ |  $$ |$$ |\$  /$$ |
#    $$ |   $$ |  $$ |$$ | \_/ $$ |
#     \|   \__|  \__|\__|     \__|▀  ¦ Source TH3jeam BY @d6d6i
#---------------------------------------------------------------------
cd $(cd $(dirname $0); pwd)
 
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`

if [ "$Version" == "18" ];then
echo -e "${GREEN}
 ▀$$$$$$$$\  $$$$$$\  $$\      $$\ 
\__$$  |$$  __$$\ $$$\    $$$ |
   $$ |   $$ /  $$ |$$$$\  $$$$ |
   $$ |   $$$$$$$$ |$$\$$\$$ $$ |
   $$ |   $$  __$$ |$$ \$$$  $$ |
   $$ |   $$ |  $$ |$$ |\$  /$$ |
   $$ |   $$ |  $$ |$$ | \_/ $$ |
   \|   \__|  \__|\__|     \__|         ¦ BY @D6D6I
 ---------------------------------------------------------------------${CNIL}"
echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
${CNIL}";
echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Th3jeam 
${CNIL}";
exit;
fi


if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3jeam${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi

if [ ! -f "./inc/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./inc/Run.lua
exit;
else
TOKEN=`cat ./inc/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
if [[ $Sudo == "" ]]; then
rm -fr ./inc/Token.txt
lua ./inc/Run.lua
exit;
fi
fi


chmod +x ./TG  
Loops=0
if [ "$1" == "R" ]; then
while [[ $Loops -le 5 ]]; do
sleep 1s
sudo rm -fr ~/.telegram-cli
./TG -s ./inc/Run.lua --bot=$TOKEN
let Plas=Loops+1
redis-cli SETEX $TOKEN 3 $Plas
Loops=`redis-cli GET ${TOKEN}`
echo $Loops
if [[ $Loops == 5 ]]; then
curl "https://api.telegram.org/bot${TOKEN}/sendmessage" -F "chat_id=${Sudo}" -F "text=THESOURCE-Reloaded-${COUNTER}-times" &>/dev/null
screen -X -S jeam quit
fi
done
else 
if [[ $Loops == 0 ]]; then
if ! screen -list | grep -q "jeam"; then
screen -S jeam ./run R
else
screen -X -S jeam quit
screen -S jeam ./run R
fi
fi
fi

